#!/bin/bash

parent_dir="$(cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd)"
codeql_db_dir="codeql-database"
build_dir="build"

cd "${parent_dir}/.."

[[ -d "${build_dir}" ]] && rm -rf "${build_dir}"
[[ -d "${codeql_db_dir}" ]] && rm -rf "${codeql_db_dir}"

codeql database create "${codeql_db_dir}" --source-root="./src" --language="cpp" --command="meson setup build" --command="ninja -C build"
