name: build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types:
      - published
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and run executable
        run: |
          cd src
          mkdir build
          cd build
          cmake ..
          cmake --build .
          ./flog
