name: dependency-review
on:
  pull_request:
    branches:
      - main
jobs:
  dependency-review:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Dependency review
        uses: actions/dependency-review-action@v3
        with:
          comment-summary-in-pr: true
          fail-on-severity: low
          vulnerability-check: true
