name: Unit tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '00 20 * * 1'
  workflow_dispatch:

permissions: read-all

jobs:
  tests:
    name: Unit tests
    strategy:
      matrix:
        os: [macos-14, macos-15, macos-15-intel, macos-26]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Harden runner
        uses: step-security/harden-runner@a90bcbc6539c36a85cdfeb73f7e2f433735f215b # v2.15.0
        with:
          egress-policy: audit
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Install dependencies
        run: brew install popt just cmocka
      - name: Run unit tests
        shell: 'script -q /dev/null bash -e {0}'  # Ensure stdin is attached to tty for unit tests
        run: just test
